// asteroid/src/examples/vue/fetch.vue
<template>
    <div class="fetch">
        <button @click="newItem">New quote</button>
        <div>{{ currentItem }}</div>
    </div>
</template>

<script lang="ts">
export default {
    data() {
        return {
            items: [],
            currentItem: "",
        };
    },
    mounted() {
        fetch("/api/fetch")
            .then((r) => r.json())
            .then((items) => (this.items = items) && this.newItem());
    },
    methods: {
        newItem() {
            this.currentItem =
                this.items[Math.floor(Math.random() * this.items.length)];
        },
    },
};
</script>

// src/examples/svelte/fetch.svelte
<script>
    import { onMount } from "svelte";
    let data = [];
    let currentItem = "";
    const newItem = () => {
        currentItem = data[Math.floor(Math.random() * data.length)];
    };

    onMount(() => {
        fetch("/api/fetch")
            .then((r) => r.json())
            .then((d) => (data = d) && newItem());
    });
</script>

<div class="fetch">
    <button on:click={newItem}>New quote</button>
    <div>{currentItem}</div>
</div>
