// src/examples/react/fetch.tsx
/** @jsxImportSource react */

import { useEffect, useState } from "react";

export default function React() {
    const [data, setData] = useState([]);
    const [currentItem, setCurrentItem] = useState("");

    const setRandom = () => {
        setCurrentItem(data[Math.floor(Math.random() * data.length)]);
    };

    useEffect(() => {
        fetch("/api/fetch")
            .then((r) => r.json())
            .then(setData);
    }, [setData]);

    useEffect(() => {
        if (data.length > 0) {
            setRandom();
        }
    }, [data, setCurrentItem]);

    return (
        <div className="fetch">
            <button onClick={setRandom}>New quote</button>
            <div>{currentItem}</div>
        </div>
    );
}

// src/examples/svelte/fetch.svelte
<script>
    import { onMount } from "svelte";
    let data = [];
    let currentItem = "";
    const newItem = () => {
        currentItem = data[Math.floor(Math.random() * data.length)];
    };

    onMount(() => {
        fetch("/api/fetch")
            .then((r) => r.json())
            .then((d) => (data = d) && newItem());
    });
</script>

<div class="fetch">
    <button on:click={newItem}>New quote</button>
    <div>{currentItem}</div>
</div>
