// asteroid/src/examples/vue/todo.vue
<template>
    <div class="todo-container">
        <p>Completed: {{ completed }}</p>
        <div class="todo-header">
            <input
                v-model="newTodo"
                @change="addTodo()"
                type="text"
            />
            <button @click="clear()">Clear</button>
        </div>
        <ul class="todo-parent">
            <li
                class="todo-item"
                v-for="(item, i) in todos"
            >
                <span :class="item.completed ? 'todo-completed' : ''">
                    {{ item.text }}
                </span>
                <button @click="toggle(i)">Toggle</button>
                <button @click="delete_(i)">Delete</button>
            </li>
        </ul>
    </div>
</template>

<script lang="ts">
type TodoItem = {
    text: string;
    completed: boolean;
};
export default {
    data() {
        return {
            todos: [] as TodoItem[],
            newTodo: "",
        };
    },
    computed: {
        completed() {
            return this.todos.filter((item) => item.completed).length;
        },
    },
    methods: {
        addTodo() {
            this.todos.push({
                text: this.newTodo,
                completed: false,
            });
            this.newTodo = "";
        },
        clear() {
            this.todos = [];
        },
        toggle(index: number) {
            this.todos[index].completed = !this.todos[index].completed;
        },
        delete_(index: number) {
            this.todos.splice(index, 1);
        },
    },
    mounted() {
        this.todos.push({
            text: "Learn web dev",
            completed: true,
        });
        this.todos.push({
            text: "Learn Vue",
            completed: false,
        });
    },
};
</script>

// src/examples/svelte/todo.svelte
<script>
    import { onMount } from "svelte";
    let todos = [];
    $: completedAmount = todos.filter((todo) => todo.completed).length;

    onMount(() => {
        todos = [
            { text: "Learn web dev", completed: true },
            { text: "Learn Svelte", completed: false },
        ];
    });

    let newTodo = "";

    function addTodo() {
        todos = [...todos, { text: newTodo, completed: false }];
        newTodo = "";
    }

    function clearTodos() {
        todos = [];
    }

    function toggleCompleted(i) {
        return () => {
            todos = todos.map((todo, index) => {
                return {
                    ...todo,
                    completed: i == index ? !todo.completed : todo.completed,
                };
            });
        };
    }

    function deleteTodo(i) {
        return () => {
            todos = todos.filter((_, index) => i !== index);
        };
    }
</script>

<div class="todo-container">
    <p>Completed: {completedAmount}</p>
    <div class="todo-header">
        <input
            bind:value={newTodo}
            on:change={addTodo}
            type="text"
        />
        <button on:click={clearTodos}>Clear</button>
    </div>
    <ul class="todo-parent">
        {#each todos as todo, i}
            <li class="todo-item">
                <span class={todo.completed ? "todo-completed" : ""}>
                    {todo.text}
                </span>
                <button on:click={toggleCompleted(i)}>Toggle</button>
                <button on:click={deleteTodo(i)}>Delete</button>
            </li>
        {/each}
    </ul>
</div>
