// src/examples/react/interval.tsx
/** @jsxImportSource react */

import { useEffect, useState } from "react";

export default function React() {
    const [count, setCount] = useState(0);

    useEffect(() => {
        const id = setInterval(() => {
            setCount((c) => c + 1);
        }, 1000);

        return () => clearInterval(id);
    }, []);

    return <span style={{ color: "lightblue" }}>{count}</span>;
}

// src/examples/vue/interval.vue
<template>
    <span>{{ counter }}</span>
</template>

<script lang="ts">
export default {
    data() {
        return {
            counter: 0,
        };
    },
    mounted() {
        setInterval(() => {
            this.counter++;
        }, 1000);
    },
};
</script>
<style>
span {
    color: lightblue;
}
</style>
