// asteroid/src/examples/vue/counter.vue
<template>
    <button @click="decrement">-</button>
    <span>{{ counter }}</span>
    <button v-on:click="increment">+</button>
</template>

<script lang="ts">
export default {
    data() {
        return {
            counter: 0,
        };
    },
    methods: {
        decrement() {
            this.counter--;
        },
        increment() {
            this.counter++;
        },
    },
};
</script>

// src/examples/react/counter.tsx
/** @jsxImportSource react */

import { useState } from "react";

export default function React() {
    const [count, setCount] = useState(0);

    const decrement = () => setCount(count - 1);
    const increment = () => setCount(count + 1);

    return (
        <>
            <button onClick={decrement}>-</button>
            <span>{count}</span>
            <button onClick={increment}>+</button>
        </>
    );
}
