// asteroid/src/examples/solid/fetch.tsx
/** @jsxImportSource solid-js */

import { createSignal, createEffect, createResource } from "solid-js";

function getData() {
    return fetch("/api/fetch").then((res) => res.json());
}

export default function Solid() {
    const [data] = createResource("", getData);
    const [currentItem, setCurrentItem] = createSignal("");

    const setRandom = () => {
        setCurrentItem(data()[Math.floor(Math.random() * data().length)]);
    };

    createEffect(() => {
        if (data.loading === false) {
            setRandom();
        }
    });

    return (
        <div className="fetch">
            <button onClick={setRandom}>New quote</button>
            <div>{currentItem()}</div>
        </div>
    );
}

// src/examples/react/fetch.tsx
/** @jsxImportSource react */

import { useEffect, useState } from "react";

export default function React() {
    const [data, setData] = useState([]);
    const [currentItem, setCurrentItem] = useState("");

    const setRandom = () => {
        setCurrentItem(data[Math.floor(Math.random() * data.length)]);
    };

    useEffect(() => {
        fetch("/api/fetch")
            .then((r) => r.json())
            .then(setData);
    }, [setData]);

    useEffect(() => {
        if (data.length > 0) {
            setRandom();
        }
    }, [data, setCurrentItem]);

    return (
        <div className="fetch">
            <button onClick={setRandom}>New quote</button>
            <div>{currentItem}</div>
        </div>
    );
}
