// src/examples/solid/interval.tsx
/** @jsxImportSource solid-js */

import { createSignal, onCleanup } from "solid-js";

export default function Solid() {
    const [count, setCount] = createSignal(0);

    const id = setInterval(() => {
        setCount((count) => count + 1);
    }, 1000);

    onCleanup(() => clearInterval(id));

    return <span style={{ color: "lightblue" }}>{count()}</span>;
}

// src/examples/react/interval.tsx
/** @jsxImportSource react */

import { useEffect, useState } from "react";

export default function React() {
    const [count, setCount] = useState(0);

    useEffect(() => {
        const id = setInterval(() => {
            setCount((c) => c + 1);
        }, 1000);

        return () => clearInterval(id);
    }, []);

    return <span style={{ color: "lightblue" }}>{count}</span>;
}
