// src/examples/solid/todo.tsx
/** @jsxImportSource solid-js */

import { For, onMount } from "solid-js";
import { createStore, produce } from "solid-js/store";

const getId = (todos) => {
    if (todos.length === 0) {
        return 0;
    }
    return todos[todos.length - 1].id + 1;
};
const addTodo = (setTodos, text, completed) =>
    setTodos(
        produce((todos) => {
            todos.push({ text, id: getId(todos), completed: completed });
        }),
    );
const addUncompletedTodo = (setTodos, text) => addTodo(setTodos, text, false);
const addCompletedTodo = (setTodos, text) => addTodo(setTodos, text, true);

const toggleTodo = (setTodos, index) =>
    setTodos(
        (todo) => index === todo.id,
        produce((todo) => (todo.completed = !todo.completed)),
    );

const deleteTodo = (setTodos, index) =>
    setTodos((todos) => todos.filter((todo) => todo.id !== index));

function TodoItem(props: {
    text: string;
    completed: boolean;
    toggle: () => void;
    delete_: () => void;
    test: () => void;
}) {
    return (
        <li class="todo-item">
            <span class={props.completed ? "todo-completed" : ""}>
                {props.text}
            </span>
            <button onClick={props.toggle}>Toggle</button>
            <button onClick={props.delete_}>Delete</button>
        </li>
    );
}

export default function Solid() {
    const [todos, setTodos] = createStore([]);

    const addUncompleted = (text) => () => addUncompletedTodo(setTodos, text);
    const addCompleted = (text) => () => addCompletedTodo(setTodos, text);
    const toggle = (index) => () => toggleTodo(setTodos, index);
    const delete_ = (index) => () => deleteTodo(setTodos, index);
    const clearTodos = () => () => setTodos([]);

    const addAction = () => (e) => {
        addUncompleted(e.target.value)();
        e.target.value = "";
    };

    onMount(() => {
        addCompleted("Learn web dev")();
        addUncompleted("Learn Solid")();
    });

    return (
        <div class="todo-container">
            <div class="todo-header">
                <input
                    type="text"
                    onChange={addAction()}
                />
                <button onClick={clearTodos()}>Clear</button>
            </div>
            <ul class="todo-parent">
                <For each={todos}>
                    {(todo, index) => (
                        <TodoItem
                            key={index}
                            text={todo.text}
                            completed={todo.completed}
                            toggle={toggle(index())}
                            delete_={delete_(index())}
                        />
                    )}
                </For>
            </ul>
        </div>
    );
}

// asteroid/src/examples/svelte/todo.svelte
<script>
    import { onMount } from "svelte";
    let todos = [];
    $: completedAmount = todos.filter((todo) => todo.completed).length;

    onMount(() => {
        todos = [
            { text: "Learn web dev", completed: true },
            { text: "Learn Svelte", completed: false },
        ];
    });

    let newTodo = "";

    function addTodo() {
        todos = [...todos, { text: newTodo, completed: false }];
        newTodo = "";
    }

    function clearTodos() {
        todos = [];
    }

    function toggle(i) {
        return () => {
            todos = todos.map((todo, index) => {
                return {
                    ...todo,
                    completed: i == index ? !todo.completed : todo.completed,
                };
            });
        };
    }

    function delete_(i) {
        return () => {
            todos = todos.filter((_, index) => i !== index);
        };
    }
</script>

<div class="todo-container">
    <p>Completed: {completedAmount}</p>
    <div class="todo-header">
        <input
            bind:value={newTodo}
            on:change={addTodo}
            type="text"
        />
        <button on:click={clearTodos}>Clear</button>
    </div>
    <ul class="todo-parent">
        {#each todos as todo, i}
            <li class="todo-item">
                <span class={todo.completed ? "todo-completed" : ""}>
                    {todo.text}
                </span>
                <button on:click={toggle(i)}>Toggle</button>
                <button on:click={delete_(i)}>Delete</button>
            </li>
        {/each}
    </ul>
</div>
